version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: tce-backend
    restart: unless-stopped
    ports:
      - "8900:8900"
    environment:
      - ENVIRONMENT=production
      - FRONTEND_URL=http://127.0.0.1:5173
      - BACKEND_HOST=0.0.0.0
      - AUTH_BASE_URL=https://ce-dev-azvasa.devstudi.com
      - USE_HTTPS=false
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=
        - VITE_TCE_API_BASE_URL=
    container_name: tce-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  # RECOMMENDED: Reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: tce-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network
  #   profiles:
  #     - proxy

networks:
  app-network:
    driver: bridge